USE [RYTreasureDB]
GO

TRUNCATE TABLE GlobalCardInfo
GO

INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(101,'骏网一卡通',5)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(101,'骏网一卡通',6)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(101,'骏网一卡通',10)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(101,'骏网一卡通',15)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(101,'骏网一卡通',20)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(101,'骏网一卡通',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(101,'骏网一卡通',50)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(101,'骏网一卡通',100)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(101,'骏网一卡通',120)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(101,'骏网一卡通',200)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(101,'骏网一卡通',300)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(101,'骏网一卡通',500)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(101,'骏网一卡通',1000)


INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',1)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',2)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',3)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',5)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',9)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',10)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',15)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',20)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',35)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',45)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',50)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',100)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',300)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',350)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(102,'盛大充值卡',1000)


INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(103,'神州行充值卡',10)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(103,'神州行充值卡',20)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(103,'神州行充值卡',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(103,'神州行充值卡',50)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(103,'神州行充值卡',100)


INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(104,'征途充值卡',10)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(104,'征途充值卡',15)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(104,'征途充值卡',20)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(104,'征途充值卡',25)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(104,'征途充值卡',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(104,'征途充值卡',50)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(104,'征途充值卡',60)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(104,'征途充值卡',100)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(104,'征途充值卡',300)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(104,'征途充值卡',468)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(104,'征途充值卡',500)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(104,'征途充值卡',1000)


INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(105,'Q币充值卡',5)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(105,'Q币充值卡',10)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(105,'Q币充值卡',15)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(105,'Q币充值卡',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(105,'Q币充值卡',60)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(105,'Q币充值卡',100)



INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(106,'联通充值卡',10)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(106,'联通充值卡',20)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(106,'联通充值卡',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(106,'联通充值卡',50)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(106,'联通充值卡',100)


INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(107,'久游充值卡',5)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(107,'久游充值卡',10)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(107,'久游充值卡',20)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(107,'久游充值卡',25)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(107,'久游充值卡',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(107,'久游充值卡',50)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(107,'久游充值卡',100)


INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',1)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',2)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',3)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',5)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',9)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',10)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',15)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',25)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',35)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',45)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',50)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',100)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',300)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',350)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(108,'易宝e卡通',1000)


INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(109,'网易充值卡',5)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(109,'网易充值卡',10)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(109,'网易充值卡',15)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(109,'网易充值卡',20)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(109,'网易充值卡',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(109,'网易充值卡',50)


INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(110,'完美充值卡',15)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(110,'完美充值卡',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(110,'完美充值卡',50)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(110,'完美充值卡',100)


INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(111,'搜狐充值卡',5)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(111,'搜狐充值卡',10)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(111,'搜狐充值卡',15)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(111,'搜狐充值卡',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(111,'搜狐充值卡',40)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(111,'搜狐充值卡',100)


INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(112,'电信充值卡',10)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(112,'电信充值卡',20)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(112,'电信充值卡',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(112,'电信充值卡',50)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(112,'电信充值卡',100)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(112,'电信充值卡',300)


INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(113,'纵游一卡通',10)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(113,'纵游一卡通',15)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(113,'纵游一卡通',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(113,'纵游一卡通',50)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(113,'纵游一卡通',100)


INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(114,'天下一卡通',5)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(114,'天下一卡通',6)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(114,'天下一卡通',10)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(114,'天下一卡通',15)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(114,'天下一卡通',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(114,'天下一卡通',50)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(114,'天下一卡通',100)


INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(115,'天宏一卡通',5)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(115,'天宏一卡通',10)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(115,'天宏一卡通',15)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(115,'天宏一卡通',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(115,'天宏一卡通',50)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(115,'天宏一卡通',100)

INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(200,'全国电话手机充值',10)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(200,'全国电话手机充值',20)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(200,'全国电话手机充值',30)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(200,'全国电话手机充值',50)
INSERT INTO GlobalCardInfo([CardID],[CardName] ,[CardQuota]) VALUES(200,'全国电话手机充值',100)

GO

TRUNCATE TABLE GlobalWebInfo
GO

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('网银充值',800,10,0,10,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('网银充值',800,30,0,30,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('网银充值',800,50,0,50,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('网银充值',800,100,0,100,4)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('支付宝充值',801,10,0,10,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('支付宝充值',801,30,0,30,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('支付宝充值',801,50,0,50,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('支付宝充值',801,100,0,100,4)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('微信充值',802,10,0,10,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('微信充值',802,30,0,30,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('微信充值',802,50,0,50,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('微信充值',802,100,0,100,4)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝支付',803,10,0,10,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝支付',803,30,0,30,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝支付',803,50,0,50,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝支付',803,100,0,100,4)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('支付宝官方充值',804,10,0,10,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('支付宝官方充值',804,30,0,30,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('支付宝官方充值',804,50,0,50,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('支付宝官方充值',804,100,0,100,4)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('微信官方充值',805,10,0,10,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('微信官方充值',805,30,0,30,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('微信官方充值',805,50,0,50,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('微信官方充值',805,100,0,100,4)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('骏网一卡通',101,5,0,5,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('骏网一卡通',101,6,0,6,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('骏网一卡通',101,10,0,10,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('骏网一卡通',101,15,0,15,4)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('骏网一卡通',101,20,0,20,5)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('骏网一卡通',101,30,0,30,6)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('骏网一卡通',101,50,0,50,7)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('骏网一卡通',101,100,0,100,8)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('骏网一卡通',101,120,0,120,9)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('骏网一卡通',101,200,0,200,10)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('骏网一卡通',101,300,0,300,11)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('骏网一卡通',101,500,0,500,12)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('骏网一卡通',101,1000,0,1000,13)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,1,0,1,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,2,0,2,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,3,0,3,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,5,0,5,4)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,9,0,9,5)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,10,0,10,6)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,15,0,15,7)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,20,0,20,8)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,30,0,30,9)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,35,0,35,10)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,45,0,45,11)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,50,0,50,12)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,100,0,100,13)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,300,0,300,14)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,350,0,350,15)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('盛大充值卡',102,1000,0,1000,16)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('神州行充值卡',103,10,0,10,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('神州行充值卡',103,20,0,20,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('神州行充值卡',103,30,0,30,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('神州行充值卡',103,50,0,50,4)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('神州行充值卡',103,100,0,100,5)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('征途充值卡',104,10,0,10,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('征途充值卡',104,15,0,15,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('征途充值卡',104,20,0,20,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('征途充值卡',104,25,0,25,4)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('征途充值卡',104,30,0,30,5)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('征途充值卡',104,50,0,50,6)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('征途充值卡',104,60,0,60,7)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('征途充值卡',104,100,0,100,8)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('征途充值卡',104,300,0,300,9)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('征途充值卡',104,468,0,468,10)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('征途充值卡',104,500,0,500,11)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('征途充值卡',104,1000,0,1000,12)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('Q币充值卡',105,5,0,5,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('Q币充值卡',105,10,0,10,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('Q币充值卡',105,15,0,15,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('Q币充值卡',105,30,0,30,4)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('Q币充值卡',105,60,0,60,5)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('Q币充值卡',105,100,0,100,6)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('联通充值卡',106,10,0,10,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('联通充值卡',106,20,0,20,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('联通充值卡',106,30,0,30,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('联通充值卡',106,50,0,50,4)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('联通充值卡',106,100,0,100,5)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('久游充值卡',107,5,0,5,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('久游充值卡',107,10,0,10,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('久游充值卡',107,20,0,20,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('久游充值卡',107,25,0,25,4)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('久游充值卡',107,30,0,30,5)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('久游充值卡',107,50,0,50,6)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('久游充值卡',107,100,0,100,7)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,1,0,1,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,2,0,2,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,3,0,3,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,5,0,5,4)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,9,0,9,5)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,10,0,10,6)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,15,0,15,7)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,25,0,25,8)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,30,0,30,9)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,35,0,35,10)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,45,0,45,11)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,50,0,50,12)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,100,0,100,13)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,300,0,300,14)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,350,0,350,15)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('易宝e卡通',108,1000,0,1000,16)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('网易充值卡',109,5,0,5,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('网易充值卡',109,10,0,10,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('网易充值卡',109,15,0,15,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('网易充值卡',109,20,0,20,4)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('网易充值卡',109,30,0,30,5)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('网易充值卡',109,50,0,50,6)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('完美充值卡',110,15,0,15,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('完美充值卡',110,30,0,30,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('完美充值卡',110,50,0,50,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('完美充值卡',110,100,0,100,4)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('搜狐充值卡',111,5,0,5,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('搜狐充值卡',111,10,0,10,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('搜狐充值卡',111,15,0,15,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('搜狐充值卡',111,30,0,30,4)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('搜狐充值卡',111,40,0,40,5)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('搜狐充值卡',111,100,0,100,6)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('电信充值卡',112,10,0,10,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('电信充值卡',112,20,0,20,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('电信充值卡',112,30,0,30,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('电信充值卡',112,50,0,50,4)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('电信充值卡',112,100,0,100,5)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('电信充值卡',112,300,0,300,6)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('纵游一卡通',113,10,0,10,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('纵游一卡通',113,15,0,15,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('纵游一卡通',113,30,0,30,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('纵游一卡通',113,50,0,50,4)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('纵游一卡通',113,100,0,100,5)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('天下一卡通',114,5,0,5,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('天下一卡通',114,6,0,6,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('天下一卡通',114,10,0,10,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('天下一卡通',114,15,0,15,4)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('天下一卡通',114,30,0,30,5)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('天下一卡通',114,50,0,50,6)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('天下一卡通',114,100,0,100,7)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('天宏一卡通',115,5,0,5,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('天宏一卡通',115,10,0,10,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('天宏一卡通',115,15,0,15,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('天宏一卡通',115,30,0,30,4)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('天宏一卡通',115,50,0,50,5)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('天宏一卡通',115,100,0,100,6)

INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('全国电话手机充值',200,10,0,10,1)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('全国电话手机充值',200,20,0,20,2)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('全国电话手机充值',200,30,0,30,3)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('全国电话手机充值',200,50,0,50,4)
INSERT INTO GlobalWebInfo([ProductName],[ProductType],[Price],[AttachCurrency] ,[PresentCurrency] ,[SortID]) VALUES('全国电话手机充值',200,100,0,100,5)

GO