USE [master]
GO

/****** Object:  Database [RYPlatformManagerDB]    Script Date: 08/24/2016 10:49:44 ******/
CREATE DATABASE [RYPlatformManagerDB] ON  PRIMARY 
( NAME = N'RY_RYPlatformManagerDB', FILENAME = N'C:\数据库\荣耀平台\RYPlatformManagerDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RY_RYPlatformManagerDB_log', FILENAME = N'C:\数据库\荣耀平台\RYPlatformManagerDB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RYPlatformManagerDB] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RYPlatformManagerDB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [RYPlatformManagerDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [RYPlatformManagerDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RYPlatformManagerDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RYPlatformManagerDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [RYPlatformManagerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RYPlatformManagerDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RYPlatformManagerDB] SET  READ_WRITE 
GO

ALTER DATABASE [RYPlatformManagerDB] SET RECOVERY FULL 
GO

ALTER DATABASE [RYPlatformManagerDB] SET  MULTI_USER 
GO

ALTER DATABASE [RYPlatformManagerDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RYPlatformManagerDB] SET DB_CHAINING OFF 
GO


