//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ClientDebug.rc 使用
//
#define IDC_EDIT_ANCHOU_PERCENT         1001
#define IDC_EDIT_ANCHOU_PERCENT_CUR     1002
#define IDC_EDIT_ANCHOU_PERCENT3        1003
#define IDC_EDIT_ANCHOU_TOTAL           1003
#define IDC_EDIT_CAI_PERCENT            1010
#define IDC_EDIT_CAI_CUR                1011
#define IDC_EDIT_CAI_CHOU_CUR           1012
#define IDC_EDIT_CAI_QIDIAN_SET         1013
#define IDC_EDIT_CAI_QIDIAN_SET2        1014
#define IDD_DIALOG_MAIN                 3100
#define IDD_CUSTOM_GENERAL              3101
#define IDD_CUSTOM_ADVANCED             3102
#define IDC_STATIC_SHOW                 3103
#define IDC_TAB_CUSTOM                  3104
#define IDD_CUSTOM_CONTROL              3104
#define IDC_STATIC1                     3319
#define IDC_EDIT1                       3319
#define IDC_EDIT_RECORD_TIME            3319
#define IDC_STATIC2                     3320
#define IDC_BUTTON1                     3320
#define IDC_BUTTON_ZHIXING              3320
#define IDC_STATIC3                     3321
#define IDC_STATIC4                     3322
#define IDC_STATIC5                     3323
#define IDC_RICHEDIT22                  3323
#define IDC_STATIC6                     3324
#define IDC_EDIT2                       3324
#define IDC_STATIC7                     3325
#define IDC_BUTTON2                     3325
#define IDC_STATIC8                     3326
#define IDC_BUTTON3                     3326
#define IDC_BUTTON4                     3327
#define IDC_STATIC9                     3327
#define IDC_BUTTON_CHOU                 3327
#define IDC_RICHEDIT23                  3328
#define IDC_EDIT3                       3329
#define IDC_LIST_USER                   3349
#define IDC_LIST_ROOM_ITEM              3350
#define IDC_STATIC_SYS                  3351
#define IDC_STATIC_ROOM                 3352
#define IDC_EDIT_ROOM_TOTAL             3352
#define IDC_STATIC_USER                 3353
#define IDC_STATIC_ROOM_T               3354
#define IDC_STATIC_SYS2                 3354
#define IDC_STATIC_USER_T               3355
#define IDC_STATIC_ROOM_T2              3355
#define IDC_STATIC_TONGJI               3356
#define IDC_STATIC_USER_T2              3356
#define IDC_STATIC_REVENUE              3357
#define IDC_RADIO_WIN                   3357
#define IDC_STATIC_T                    3358
#define IDC_RADIO_LOSE                  3358
#define IDC_STATIC_SET                  3359
#define IDC_STATIC_CHOU                 3360
#define IDC_STATIC_T2                   3361
#define IDC_STATIC_SETTING              3362
#define IDC_STATIC_ROOM_T3              3362
#define IDC_STATIC_T3                   3363
#define IDC_EDIT_CONFIG_SYSSTORAGE      4000
#define IDC_EDIT_CONFIG_PLAYERSTORAGE   4001
#define IDC_EDIT_CONFIG_PARAMETER_K     4002
#define IDC_CHECK_SYSCTRL_STORAGE_DEADLINE 4003
#define IDC_EDIT_RESET_PERCENT          4003
#define IDC_EDIT_CONFIG_SYSSTORAGE2     4004
#define IDC_EDIT_SYS_WINTOTAL           4004
#define IDC_BUTTON_SETRULE              4005
#define IDC_STATIC_CUR_SYSSTORAGE       4006
#define IDC_STATIC_CUR_PLAYERSTORAGE    4007
#define IDC_STATIC_CUR_PARAMETER_K      4008
#define IDC_STATIC_SYS_CTRLDESC         4009
#define IDC_STATIC_SYSCTRL_RESETCOUNT   4010
#define IDC_STATIC_SYSCTRL_DEADLINELIMIT 4011
#define IDC_EDIT_RESET_PERCENT_ROOM     4011
#define IDC_STATIC_SYS_CTRLDESC2        4011
#define IDC_STATIC_SYSCTRL_SYSWIN       4012
#define IDC_SERVICE_SYS_WINTOTAL        4013
#define IDC_EDIT_ROOMCTRL_SYSSTORAGE    4014
#define IDC_EDIT_ROOMCTRL_PLAYERSTORAGE 4015
#define IDC_EDIT_ROOMCTRL_PARAMETER_K   4016
#define IDC_CHECK_ROOMCTRL_STORAGE_DEADLINE 4017
#define IDC_EDIT_RESET_PERCENT3         4017
#define IDC_EDIT_RESET_PERCENT_USER     4017
#define IDC_BUTTON_SETRULE2             4017
#define IDC_BUTTON_CANCELL_ROOM         4017
#define IDC_BTN_SET_ROOMCTRL            4018
#define IDC_STATIC_ROOMCTRL_ID          4019
#define IDC_STATIC_ROOMCTRL_SYSSTORAGE  4020
#define IDC_STATIC_ROOMCTRL_PLAYERSTORAGE 4021
#define IDC_STATIC_ROOM_CTRLDESC        4022
#define IDC_STATIC_ROOMCTRL_PARAMETER_K 4023
#define IDC_STATIC_ROOMCTRL_DEADLINELIMIT 4024
#define IDC_STATIC_ROOMCTRL_SYSWIN      4025
#define IDC_STATIC_ROOMCTRL_SYSWIN2     4026
#define IDC_RADIO_LONG                  4027
#define IDC_EDIT_USERCTRL_SYSSTORAGE    4027
#define IDC_RADIO_PING                  4028
#define IDC_EDIT_USERCTRL_PLAYERSTORAGE 4028
#define IDC_RADIO_HU                    4029
#define IDC_EDIT_USERCTRL_PARAMETER_K   4029
#define IDC_RADIO_SYS_LOST              4030
#define IDC_BTN_SET_USERCTRL            4030
#define IDC_RADIO_SYS_WIN               4031
#define IDC_CHECK_USERCTRL_STORAGE_DEADLINE 4031
#define IDC_BTN_QUARY                   4031
#define IDC_EDIT_USERCTRL_SYSSTORAGE2   4032
#define IDC_EDIT_USERID                 4032
#define IDC_EDIT_USERID_DEBUG           4033
#define IDC_BTN_DEBUG_EXC               4034
#define IDC_BTN_DEBUG_CANCELL           4035
#define IDC_COMBO_TIMES                 4037
#define IDC_BTN_SET_AREACTRL            4038
#define IDC_STATIC_AREACTRL_POS         4040
#define IDC_STATIC_AREACTRL_ID          4041
#define IDC_STATIC_AREACTRL_REMAINCOUNT 4042
#define IDC_STATIC_AREACTRL_SYSWIN      4043
#define IDC_STATIC_AREACTRL_PLAYERWIN   4044
#define IDC_BTN_CANCEL_AREACTRL         4045
#define IDC_STATIC_USERCTRL_SYSSTORAGE  4045
#define IDC_STATIC_AREACTRL_CONFIGCOUNT 4046
#define IDC_STATIC_USERCTRL_SYSSTORAGE2 4046
#define IDC_STATIC_USERCTRL_PLAYERSTORAGE 4047
#define IDC_STATIC_USERCTRL_PARAMETER_K 4048
#define IDC_STATIC_USER_CTRLDESC        4049
#define IDC_STATIC_USERCTRL_ID          4050
#define IDC_STATIC_USERCTRL_DEADLINELIMIT 4051
#define IDC_STATIC_USERCTRL_PLAYERSTORAGE2 4051
#define IDC_STATIC_USERCTRL_SYSWIN      4052
#define IDC_STATIC_USER_CTRLDESC2       4053
#define IDC_STATIC_USERCTRL_ID2         4054
#define IDC_STATIC_USERCTRL_SYSSTORAGE3 4055
#define IDC_STATIC_USERCTRL_ID3         4056
#define IDC_LIST_SYSSTORAGE             4100
#define IDC_STATIC_LIST_SYSSTORAGE_SYSWIN 4101
#define IDC_LIST_DESK                   4101
#define IDC_STATIC_LIST_SYSSTORAGE_PLAYERWIN 4102
#define IDC_LIST_ROOM                   4103
#define IDC_STATIC_LIST_ROOM_SYSWIN     4104
#define IDC_STATIC_LIST_ROOM_PLAYERWIN  4105
#define IDC_BTN_CANCEL_ROOMCTRL         4106
#define IDC_STATIC_LIST_USER_SYSWIN     4107
#define IDC_BTN_CANCEL_USER             4107
#define IDC_BTN_CANCEL_ROOMCTRL2        4107
#define IDC_STATIC_LIST_AREACTRL_SYSWIN 4108
#define IDC_STATIC_LIST_USER_PLAYERWIN  4108
#define IDC_STATIC_LIST_AREACTRL_PLAYERWIN 4109
#define IDC_LIST_USERSTORAGE            4109
#define IDC_BTN_CANCEL_USERCTRL         4110
#define IDC_STATIC_TOTAL_SYSWIN         4111
#define IDC_BTN_CANCEL_USERCTRL2        4111
#define IDC_STATIC_TOTAL_SYSWIN2        4112
#define IDC_STATIC_CAI                  4112
#define IDC_BTN_CANCEL_USERCTRL3        4112
#define IDC_BTN_CLEAR_DESKALL           4112
#define IDC_STATICT_TOTAL_PLAYERWIN     4113
#define IDC_BTN_CLEAR_DESK              4113
#define IDC_BTN_USER_BET_ALL            4114
#define IDC_LIST_USER_BET               4115
#define IDC_STATIC_BEGIN_RECORDTIME     4116
#define IDC_STATIC_SYS_RESET_PERCENT    4117
#define IDC_EDIT_RESET_PERCENT_ROOM2    4118
#define IDC_STATIC_SYS_ZHONG_PERCENT    4119

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3307
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3358
#define _APS_NEXT_SYMED_VALUE           3305
#endif
#endif
