//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 GameServer.rc 使用
//
#define IDD_CUSTOM_RULE                 9
#define IDD_PERSONAL_RULE               10
#define IDC_EDIT_ROOMSTORAGE_START      201
#define IDC_EDIT_ROOMSTORAGE_DEDUCT     202
#define IDC_EDIT_ROOMSTORAGE_MAX1       203
#define IDC_EDIT_ROOMSTORAGE_MUL1       204
#define IDC_EDIT_ROOMSTORAGE_MAX2       205
#define IDC_EDIT_ROOMSTORAGE_MUL2       206
#define IDC_ROBOT_SCOREMIN              207
#define IDC_ROBOT_BANKERGETBANKER       208
#define IDC_ROBOT_SCOREMAX              209
#define IDC_ROBOT_BANKGET               210
#define IDC_ROBOT_STOMUL                211
#define IDC_RADIO_CT_CLASSIC            214
#define IDC_RADIO_CT_ADDTIMES           215
#define IDC_RADIO_ST_SENDFOUR           216
#define IDC_RADIO_ST_BETFIRST           217
#define IDC_RADIO_HAVEKING              218
#define IDC_RADIO_NOKING                219
#define IDC_RADIO_DESPOT_BANKER         220
#define IDC_RADIO_ROB_BANKER            221
#define IDC_RADIO_NIUNIU_BANKER         222
#define IDC_RADIO_NONIUNIU              223
#define IDC_RADIO_BT_FREE               224
#define IDC_RADIO_BT_PERCENT            225
#define IDC_EDIT_BT_FREE_0              226
#define IDC_EDIT_BT_FREE_1              227
#define IDC_EDIT_BT_FREE_2              228
#define IDC_EDIT_BT_FREE_3              229
#define IDC_EDIT_BT_FREE_4              230
#define IDC_EDIT_BT_PERCENT_0           231
#define IDC_EDIT_BT_PERCENT_1           232
#define IDC_EDIT_BT_PERCENT_2           233
#define IDC_EDIT_BT_PERCENT_3           234
#define IDC_EDIT_BT_PERCENT_4           235
#define IDC_EDIT_CARDTYPETIMES_0        236
#define IDC_EDIT_CARDTYPETIMES_1        237
#define IDC_EDIT_CARDTYPETIMES_2        238
#define IDC_EDIT_CARDTYPETIMES_3        239
#define IDC_EDIT_CARDTYPETIMES_4        240
#define IDC_EDIT_CARDTYPETIMES_5        241
#define IDC_EDIT_CARDTYPETIMES_6        242
#define IDC_EDIT_CARDTYPETIMES_7        243
#define IDC_EDIT_CARDTYPETIMES_8        244
#define IDC_EDIT_CARDTYPETIMES_9        245
#define IDC_EDIT_CARDTYPETIMES_10       246
#define IDC_EDIT_CARDTYPETIMES_11       247
#define IDC_EDIT_CARDTYPETIMES_12       248
#define IDC_EDIT_CARDTYPETIMES_13       249
#define IDC_EDIT_CARDTYPETIMES_14       250
#define IDC_EDIT_CARDTYPETIMES_15       251
#define IDC_EDIT_CARDTYPETIMES_16       252
#define IDC_EDIT_CARDTYPETIMES_17       253
#define IDC_EDIT_CARDTYPETIMES_18       254
#define IDC_RADIO_CTTIMES_CONFIG_0      255
#define IDC_RADIO_CTTIMES_CONFIG_1      256
#define IDC_RADIO_FREEBANKER            257
#define IDC_RADIO_TONGBI                258
#define IDC_EDIT_TRUSTEEDELAY_TIME      259
#define IDC_EDIT5                       6051
#define IDC_EDIT1                       6052
#define IDC_EDIT2                       6053
#define IDC_EDIT3                       6054
#define IDC_EDIT4                       6055
#define IDC_EDIT6                       6056
#define IDC_TIME_START_GAME5            6057
#define IDC_TIME_START_GAME6            6058
#define IDC_TIME_START_GAME7            6059
#define IDC_TIME_START_GAME8            6060
#define IDC_TIME_START_GAME9            6061
#define IDC_TIME_START_GAME10           6062
#define IDC_TIME_START_GAME11           6063
#define IDC_TIME_START_GAME12           6064
#define IDC_TIME_START_GAME13           6065
#define IDC_TIME_START_GAME14           6066
#define IDC_TIME_START_GAME15           6067
#define IDC_TIME_START_GAME16           6068
#define IDC_TIME_START_GAME17           6069
#define IDC_TIME_START_GAME18           6070
#define IDC_TIME_START_GAME19           6071
#define IDC_TIME_START_GAME20           6072
#define IDC_TIME_START_GAME21           6073
#define IDC_TIME_START_GAME22           6074
#define IDC_TIME_START_GAME23           6075
#define IDC_TIME_START_GAME24           6076
#define IDC_CHECK_BGT_DESPOT_           6077
#define IDC_CHECK_BGT_ROB_              6078
#define IDC_CHECK_BGT_NIUNIU_           6079
#define IDC_CHECK_BGT_NONIUNIU_         6080
#define IDC_CHECK_BGT_FREEBANKER_       6081
#define IDC_CHECK_BGT_TONGBI_           6082
#define IDC_CHECK_CT_CLASSIC_           6083
#define IDC_CHECK_CT_ADDTIMES_          6084
#define _APS_NEXT_DEBUG_VALUE           6084
#define IDC_EDIT_BEBANKER_CON0          6085
#define IDC_EDIT_BEBANKER_CON1          6086
#define IDC_EDIT_BEBANKER_CON2          6087
#define IDC_EDIT_BEBANKER_CON3          6088
#define IDC_EDIT_USERBETTIMES_0         6089
#define IDC_EDIT_USERBETTIMES_1         6090
#define IDC_EDIT_USERBETTIMES_2         6091
#define IDC_EDIT_USERBETTIMES_3         6092
#define IDC_CHECK_SENDFOUR              6093
#define IDC_CHECK_NEEDPW                6094
#define IDC_CHECK_FORBIDJOIN            6095
#define IDC_CHECK_FORBIDCUO             6096
#define IDC_CHECK_RC_OFFLINETRUSTEE     6097
#define IDC_CHECK_FOURFLOWER            6098
#define IDC_CHECK_FIVEFLOWER            6099
#define IDC_CHECK_SHUNZI                6100
#define IDC_CHECK_SAMEFLOWER            6101
#define IDC_CHECK_HULU                  6102
#define IDC_CHECK_BOMB                  6103
#define IDC_CHECK_TONGHUASHUN           6104
#define IDC_CHECK_FIVESNIUNIU           6105
#define IDC_CHECK_HAVEKING              6106

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
