USE RYPlatformDB
GO

TRUNCATE TABLE GamePropertyRelat
set IDENTITY_INSERT GamePropertyRelat ON
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	1	,	1	,	0	,	3	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	2	,	2	,	0	,	3	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	3	,	3	,	0	,	3	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	4	,	4	,	0	,	3	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	5	,	5	,	0	,	3	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	6	,	6	,	0	,	3	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	7	,	7	,	0	,	3	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	8	,	8	,	0	,	3	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	9	,	9	,	0	,	3	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	10	,	10	,	0	,	3	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	11	,	11	,	0	,	3	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	12	,	12	,	0	,	3	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	13	,	13	,	0	,	3	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	14	,	101	,	0	,	1	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	15	,	102	,	0	,	1	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	16	,	103	,	0	,	1	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	17	,	104	,	0	,	1	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	18	,	105	,	0	,	1	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	19	,	201	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	20	,	202	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	21	,	203	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	22	,	204	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	23	,	205	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	24	,	206	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	25	,	207	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	26	,	208	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	27	,	209	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	28	,	210	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	29	,	211	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	30	,	212	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	31	,	301	,	0	,	1	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	32	,	302	,	0	,	1	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	33	,	303	,	0	,	1	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	34	,	304	,	0	,	1	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	35	,	305	,	0	,	1	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	36	,	306	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	37	,	307	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	38	,	308	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	39	,	309	,	0	,	2	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	40	,	101	,	1	,	5	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	41	,	102	,	1	,	5	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	42	,	103	,	1	,	5	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	43	,	104	,	1	,	5	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	44	,	105	,	1	,	5	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	45	,	201	,	1	,	8	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	46	,	202	,	1	,	8	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	47	,	203	,	1	,	8	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	48	,	204	,	1	,	8	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	49	,	205	,	1	,	8	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	50	,	206	,	1	,	8	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	51	,	207	,	1	,	8	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	52	,	208	,	1	,	8	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	53	,	209	,	1	,	8	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	54	,	210	,	1	,	8	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	55	,	211	,	1	,	8	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	56	,	212	,	1	,	8	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	57	,	301	,	1	,	7	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	58	,	302	,	1	,	7	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	59	,	303	,	1	,	7	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	60	,	304	,	1	,	7	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	61	,	305	,	1	,	7	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	62	,	306	,	1	,	8	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	63	,	308	,	1	,	8	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	64	,	309	,	1	,	8	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	65	,	501	,	1	,	5	)
insert GamePropertyRelat(ID,PropertyID,TagID,TypeID) values(	66	,	501	,	1	,	8	)

set IDENTITY_INSERT GamePropertyRelat OFF