//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ClientDebug.rc 使用
//
#define IDC_EDIT_CONFIG_TAX_RATIO       1001
#define IDC_STATIC_CUR_TAX_RATIO        1002
#define IDC_STATIC_CUR_TAX_TOTAL        1003
#define IDC_EDIT_CONFIG_REWARD_RATIO    1010
#define IDC_STATIC_CUR_REWARD_STROAGE   1011
#define IDC_STATIC_CUR_REWARD_RATIO     1012
#define IDC_EDIT_CONFIG_REWARD_DISPATCH_START 1013
#define IDC_EDIT_CONFIG_REWARD_VIRTUAL_STORAGE 1014
#define IDC_EDIT_CONFIG_REWARD_DISPATCH_RATIO 1015
#define IDD_DIALOG_MAIN                 3100
#define IDD_CUSTOM_CONFIG               3101
#define IDD_CUSTOM_LOG                  3102
#define IDC_STATIC_SHOW                 3103
#define IDD_CUSTOM_DEBUG                3104
#define IDC_TAB_CUSTOM                  3105
#define IDD_CUSTOM_WEIGHT               3306
#define IDC_EDIT_CONFIG_FREE_GAME_RATIO 3319
#define IDC_BUTTON_CONFIG_GAME_EXTRA    3320
#define IDC_EDIT_RAID15                 3321
#define IDC_EDIT_RAID20                 3322
#define IDC_EDIT_RAID25                 3323
#define IDC_EDIT_CONFIG_EXTRA_GAME_RATIO 3324
#define IDC_BUTTON_REWARD_SET           3325
#define IDC_EDIT_RAID75                 3326
#define IDC_STATIC9                     3327
#define IDC_RICHEDIT23                  3328
#define IDC_EDIT3                       3329
#define IDC_EDIT_STORGAE_SET_MIN_VALUE  3329
#define IDC_EDIT_RAID5                  3331
#define IDC_BUTTON5                     3332
#define IDC_BUTTON_CONFIG_WEIGHT        3332
#define IDC_EDIT4                       3333
#define IDC_EDIT5                       3334
#define IDC_EDIT6                       3335
#define IDC_EDIT7                       3336
#define IDC_EDIT_RAID150                3337
#define IDC_EDIT_RAID200                3338
#define IDC_EDIT_RAID400                3339
#define IDC_EDIT_RAID800                3340
#define IDC_EDIT8                       3341
#define IDC_EDIT9                       3342
#define IDC_EDIT10                      3343
#define IDC_EDIT11                      3344
#define IDC_EDIT12                      3345
#define IDC_EDIT13                      3346
#define IDC_EDIT14                      3347
#define IDC_EDIT15                      3348
#define IDC_LIST_USER                   3349
#define IDC_LIST_PLAYER_WORKING_TASK    3349
#define IDC_LIST_ROOM_ITEM              3350
#define IDC_LIST_ROOM_WORKING_TASK      3350
#define IDC_STATIC_SYS                  3351
#define IDC_STATIC_ROOM                 3352
#define IDC_STATIC_USER                 3353
#define IDC_STATIC_ROOM_T               3354
#define IDC_STATIC_USER_T               3355
#define IDC_STATIC_TONGJI               3356
#define IDC_STATIC_REVENUE              3357
#define IDC_STATIC_T                    3358
#define IDC_STATIC_SET                  3359
#define IDC_STATIC_CHOU                 3360
#define IDC_STATIC_TITAL                3361
#define IDC_STATIC_T2                   3361
#define IDC_STATIC_SETTING              3362
#define IDC_BUTTON_WEIGHT               3363
#define IDC_BUTTON_ROOM_CANCEL          3364
#define IDC_BUTTON_PLAYER_CANCEL        3365
#define IDC_EDIT_CONFIG_STORAGE_SYSTEM  4000
#define IDC_EDIT_CONFIG_STORAGE_PLAYER  4001
#define IDC_EDIT_CONFIG_STORAGE_PARATERMK 4002
#define IDC_EDIT_CONFIG_STORAGE_FORCE_REST_SECTION 4003
#define IDC_STATIC_TOTAL_WINLOSE        4004
#define IDC_BUTTON_STORAGE_SET          4005
#define IDC_STATIC_CUR_STORAGE_SYATEM   4006
#define IDC_STATIC_CUR_STORAGE_PLAYER   4007
#define IDC_STATIC_CUR_STORAGE_PARAMTERMK 4008
#define IDC_STATIC_CUR_STORAGE_WIN_RATIO 4009
#define IDC_STATIC_CUR_STORAGE_RESET_TIMES 4010
#define IDC_EDIT_CONFIG_ROOM_FROCE_RESET_SECTION 4011
#define IDC_STATIC_CUR_STORAGE_SYATEM_WINLOSE 4012
#define IDC_STATIC_TOTAL_TAX            4013
#define IDC_EDIT_CONFIG_ROOM_SYSTEM     4014
#define IDC_EDIT_CONFIG_ROOM_PLAYER     4015
#define IDC_EDIT_CONFIG_ROOM_PARAMTERMK 4016
#define IDC_EDIT_CONFIG_PLAYER_FORCERESETSECTION 4017
#define IDC_BUTTON_ROOM_SET             4018
#define IDC_STATIC_CUR_ROOM_STORAGE_INDEX 4019
#define IDC_STATIC_CUR_ROOM_SYSTEM_STORAGE 4020
#define IDC_STATIC_CUR_ROOM_PLAYER_STORAGE 4021
#define IDC_STATIC_CUR_ROOM_WIN_RATIO   4022
#define IDC_STATIC_CUR_ROOM_PARAMTERMK  4023
#define IDC_STATIC_ROOMCTRL_DEADLINELIMIT 4024
#define IDC_EDIT_STORAGE_SET_MIN_VALUE2 4024
#define IDC_STATIC_CUR_ROOM_TOTAL_WINLOSE 4025
#define IDC_EDIT_CONFIG_ROOM_PLAYER3    4026
#define IDC_EDIT_STORAGE_SET_MIN_VALUE3 4026
#define IDC_EDIT_CONFIG_PLAYER_SYSTEMSTORAGE 4027
#define IDC_EDIT_CONFIG_PLAYER_PLAYERSTORAGE 4028
#define IDC_EDIT_CONFIG_PLAYER_PARAMTERMK 4029
#define IDC_BUTTON_PLAYER_SET           4030
#define IDC_CHECK_USERCTRL_STORAGE_DEADLINE 4031
#define IDC_EDIT_CONFIG_PLAYER_DEBUGID  4032
#define IDC_COMBO_TIMES                 4037
#define IDC_BTN_SET_AREACTRL            4038
#define IDC_STATIC_AREACTRL_POS         4040
#define IDC_STATIC_AREACTRL_ID          4041
#define IDC_STATIC_AREACTRL_REMAINCOUNT 4042
#define IDC_STATIC_AREACTRL_SYSWIN      4043
#define IDC_STATIC_AREACTRL_PLAYERWIN   4044
#define IDC_STATIC_CUR_PLAYER_SYSTEM_STORAGE 4045
#define IDC_STATIC_AREACTRL_CONFIGCOUNT 4046
#define IDC_STATIC_CUR_PLAYER_PLAYER_STORAGE 4047
#define IDC_STATIC_CUR_PLAYER_PARAMTERMK 4048
#define IDC_STATIC_CUR_PLAYER_WIN_RATIO 4049
#define IDC_STATIC_CUR_PLAYER_DEBUGID   4050
#define IDC_STATIC_USERCTRL_DEADLINELIMIT 4051
#define IDC_STATIC_CUR_PLAYER_TOTAL_WINLOSE 4052
#define IDC_LIST_SYSTEM_ALL_TASK        4100
#define IDC_STATIC_LIST_SYSSTORAGE_SYSWIN 4101
#define IDC_STATIC_LIST_SYSSTORAGE_PLAYERWIN 4102
#define IDC_LIST_ROOM_ALL_TASK          4103
#define IDC_STATIC_LIST_ROOM_SYSWIN     4104
#define IDC_STATIC_LIST_ROOM_PLAYERWIN  4105
#define IDC_BTN_ROOM_DELETE             4106
#define IDC_BTN_ROOM_DELETE_ALL         4107
#define IDC_STATIC_LIST_USER_PLAYERWIN  4108
#define IDC_LIST_PLAYER_ALL_TASK        4109
#define IDC_BTN_PLAYER_DELETE_ALL       4110
#define IDC_BTN_PLAYER_DELETE           4111
#define IDC_STATIC_CAI                  4112
#define IDC_STATICT_TOTAL_PLAYERWIN     4113
#define IDC_BTN_USER_BET_ALL            4114
#define IDC_LIST_USER_BET               4115
#define IDC_STATIC_BEGIN_RECORDTIME     4116
#define IDC_STATIC_TYPE                 5000
#define IDC_STATIC_WEIGHT               5001
#define IDC_STATIC_RATIO                5002
#define IDC_STATIC_TYPE1                5003
#define IDC_STATIC_WEIGHT1              5004
#define IDC_STATIC_RATIO1               5005
#define IDC_STATIC_TYPE2                5006
#define IDC_STATIC_WEIGHT2              5007
#define IDC_STATIC_RATIO2               5008
#define IDC_STATIC_TYPE3                5009
#define IDC_STATIC_WEIGHT3              5010
#define IDC_STATIC_RATIO3               5011
#define IDC_STATIC_TYPE4                5012
#define IDC_STATIC_WEIGHT4              5013
#define IDC_STATIC_RATIO4               5014
#define IDC_STATIC_TYPE5                5015
#define IDC_STATIC_WEIGHT5              5016
#define IDC_STATIC_RATIO5               5017
#define IDC_STATIC_TYPE6                5018
#define IDC_STATIC_WEIGHT6              5019
#define IDC_STATIC_RATIO6               5020
#define IDC_STATIC_TYPE7                5021
#define IDC_STATIC_WEIGHT7              5022
#define IDC_STATIC_RATIO7               5023
#define IDC_STATIC_TYPE8                5024
#define IDC_STATIC_WEIGHT8              5025
#define IDC_STATIC_RATIO8               5026
#define IDC_STATIC_TYPE9                5027
#define IDC_STATIC_WEIGHT9              5028
#define IDC_STATIC_RATIO9               5029
#define IDC_STATIC_TYPE10               5030
#define IDC_STATIC_WEIGHT10             5031
#define IDC_STATIC_RATIO10              5032
#define IDC_STATIC_TYPE11               5033
#define IDC_STATIC_WEIGHT11             5034
#define IDC_STATIC_RATIO11              5035
#define IDC_STATIC_TYPE12               5036
#define IDC_STATIC_WEIGHT12             5037
#define IDC_STATIC_RATIO12              5038
#define IDC_STATIC_TYPE13               5039
#define IDC_STATIC_WEIGHT13             5040
#define IDC_STATIC_RATIO13              5041

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3307
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3379
#define _APS_NEXT_SYMED_VALUE           3305
#endif
#endif
